### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by videate-josh** [argos-ci/argos-javascript#140]
## Bug description

When I try to use a shared playwright config I'm running into the following:

```bash
prompt$ npx playwright test 
.....
Error: Cannot find module '@argos-ci/playwright/reporter'
Require stack:
- not-shared-repo/node_modules/playwright/lib/common/config.js
- not-shared-repo/node_modules/playwright/lib/reporters/json.js
- not-shared-repo/node_modules/playwright/lib/runner/reporters.js
- not-shared-repo/node_modules/playwright/lib/runner/runner.js
- not-shared-repo/node_modules/playwright/lib/program.js
- not-shared-repo/node_modules/@playwright/test/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at not-shared-repo/node_modules/playwright/lib/common/config.js:206:21
    at Array.map (<anonymous>)
    at resolveReporters (not-shared-repo/node_modules/playwright/lib/common/config.js:204:110)
    at new FullConfigInternal (not-shared-repo/node_modules/playwright/lib/common/config.js:78:56)
    at loadConfig (not-shared-repo/node_modules/playwright/lib/common/configLoader.js:103:22)
    at loadConfigFromFileRestartIfNeeded (not-shared-repo/node_modules/playwright/lib/common/configLoader.js:258:10)
    at runTests (not-shared-repo/node_modules/playwright/lib/program.js:194:18)
    at t.<anonymous> (not-shared-repo/node_modules/playwright/lib/program.js:54:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'not-shared-repo/node_modules/playwright/lib/common/config.js',
    'not-shared-repo/node_modules/playwright/lib/reporters/json.js',
    'not-shared-repo/node_modules/playwright/lib/runner/reporters.js',
    'not-shared-repo/node_modules/playwright/lib/runner/runner.js',
    'not-shared-repo/node_modules/playwright/lib/program.js',
    'not-shared-repo/node_modules/@playwright/test/cli.js'
  ]
}
```

Here is how I'm implementing the shared config:
```typescript
import { PlaywrightTestConfig, defineConfig, devices, ReporterDescription } from '@playwright/test';
export type { PlaywrightTestConfig, ReporterDescription };
export { defineConfig, devices };

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export const sharedPlaywrightConfig: PlaywrightTestConfig = defineConfig({
  testDir: './e2e-tests',
  testMatch: '*e2e-tests/**/*.spec.ts',
  /* To Turn Off ZenDesk and LogRocket */
  // globalSetup: './global-setup',
  /* 10 min global timeout */
  globalTimeout: 10 * 60 * 1000,
  /* 5 minutes single test timeout */
  timeout: 300000,
  /* Expect timeout for selector */
  expect: { timeout: 10000 },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 3 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    ['dot'],
    ['json', { outputFile: 'testResults.json' }],
    ['html'],
    [
      '@argos-ci/playwright/reporter',
      {
        root: './screenshots',
        uploadToArgos: !!process.env.CI,
        token: process.env.ARGOS_TOKEN,
        buildName: process.env.ARGOS_SERVICE || 'console2-dev',
      },
    ],
  ],
  /* Hoping this enables logging of slow tests */
  // reportSlowTests: null,
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    actionTimeout: 10000,
    /* Default to this for test-id lookup */
    testIdAttribute: 'data-videate-selector',
    /* Allow browser clipboard read and write */
    permissions: ['clipboard-read', 'clipboard-write'],

    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: `${process.env.PLAYWRIGHT_BASE_URL}`,
    /* Skip for testing purposes */
    bypassCSP: true,
    ignoreHTTPSErrors: true,

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on',

    viewport: {
      width: 1920,
      height: 1080,
    },
  },

  /* Configure projects for major browsers */
  projects: [
    // { name: 'setup', testMatch: 'global-login-auth.setup.ts' },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        viewport: {
          width: 1920,
          height: 1080,
        },
      },
    },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});
```

### Correct behavior expected

I would assume it could load and find the argos reporter from the repo that importing the shared test lib

### Wrong behavior observed

See above

### Screenshot

_Optional:_ Add a screenshot to help explain the problem.

## Reproduce

Describe a way to reproduce the bug.

You can share a code snippet or give a step by step guide.

## Setup

Describe the setup you have when you encounter the bug : device, browser, library version...

## Additional information

Add any other information that can help us understand the bug or fix it.

**Comment by videate-josh** [comment]
It seems this issue was due to a malformed package-lock.json. Going to close.
